apiVersion: v2
name: vmonitor-metric-agent
description: vMonitor Platform Metric Agent
keywords:
  - monitoring
  - alerting
  - metric
home: https://www.vngcloud.vn
maintainers:
  - name: VNGCloud
    email: support@vngcloud.vn
dependencies:
- condition: vmonitor.kubeStateMetricsEnabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.20.0
version: 0.2.0
appVersion: "1.26.2"
